/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.Review;
import java.awt.Cursor;

/**
 *
 * @author huunh
 */
public class PanelReview extends javax.swing.JPanel {

    /**
     * Creates new form PanelReview
     */
    private Review review;
    public PanelReview(Review review) {
        this.review = review;
        initComponents();
        lblReviewLink.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblReviewTitle.setText(review.getTitle());
        lblReviewLink.setText(review.getURL());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReviewLink = new javax.swing.JLabel();
        lblReviewTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(32, 32, 32));
        setMinimumSize(new java.awt.Dimension(1310, 0));
        setPreferredSize(new java.awt.Dimension(1320, 80));

        lblReviewLink.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        lblReviewLink.setForeground(new java.awt.Color(0, 153, 255));
        lblReviewLink.setText("https://ww.yan.vn/review-phim-muoi-loi-nguyen-tro-lai-hoi-3-be-cua-khet-let-chi-pu-hong-anh-toa-sang-3140109.html");

        lblReviewTitle.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblReviewTitle.setForeground(new java.awt.Color(240, 240, 240));
        lblReviewTitle.setText("Review phim Mười - Lời Nguyền Trở Lại: Hồi 3 bẻ cua khét lẹt, Chi Pu - Hồng Ánh tỏa sáng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReviewTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReviewLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReviewTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReviewLink)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblReviewLink;
    private javax.swing.JLabel lblReviewTitle;
    // End of variables declaration//GEN-END:variables
}
