/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JPanel;

/**
 *
 * @author huunh
 */
public class PanelListHourSchedule extends javax.swing.JPanel {

    /**
     * Creates new form PanelListHourSchedule
     */
    public PanelListHourSchedule(String str) {
        initComponents();
        lblCategory.setText(str);
        pnlListHourSchedule.setLayout(new GridLayout(0,6,10,10));
        for(int i =0;i<10;i++){
            JPanel pnl = new JPanel();
            pnl.add(new GUI.PanelHourSchedule());
            pnl.setPreferredSize(new Dimension(120,50));
            pnl.setBackground(Color.decode("#202020"));
            pnlListHourSchedule.add(pnl);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCategory = new javax.swing.JLabel();
        pnlListHourSchedule = new javax.swing.JPanel();

        setBackground(new java.awt.Color(32, 32, 32));

        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setText("jLabel1");

        pnlListHourSchedule.setBackground(new java.awt.Color(32, 32, 32));

        javax.swing.GroupLayout pnlListHourScheduleLayout = new javax.swing.GroupLayout(pnlListHourSchedule);
        pnlListHourSchedule.setLayout(pnlListHourScheduleLayout);
        pnlListHourScheduleLayout.setHorizontalGroup(
            pnlListHourScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlListHourScheduleLayout.setVerticalGroup(
            pnlListHourScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlListHourSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCategory)
                        .addGap(0, 996, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListHourSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCategory;
    private javax.swing.JPanel pnlListHourSchedule;
    // End of variables declaration//GEN-END:variables
}
