/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author huunh
 */
public class PanelMovie extends javax.swing.JPanel {

    /**
     * Creates new form PanelMovie
     */
    public PanelMovie() throws IOException {
        initComponents();
        setData();
    }
    public void setData() throws MalformedURLException, IOException{
        URL url = new URL("https://traffic-edge19.cdn.vncdn.io/cinema/img/81593614129596321-bxp5IUY05jLGeZ5bW85W2NF6Rgi.jpg");
        BufferedImage c = ImageIO.read(url);
        ImageIcon image = new ImageIcon(c);
        Image fixImage = image.getImage().getScaledInstance(200, 225, java.awt.Image.SCALE_SMOOTH);
        image = new ImageIcon(fixImage);
        lblImage.setIcon(image);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        lblNameMovie = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();

        setBackground(new java.awt.Color(32, 32, 32));
        setMaximumSize(new java.awt.Dimension(200, 300));
        setMinimumSize(new java.awt.Dimension(200, 300));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(200, 300));

        lblImage.setMaximumSize(new java.awt.Dimension(170, 190));
        lblImage.setMinimumSize(new java.awt.Dimension(170, 190));
        lblImage.setPreferredSize(new java.awt.Dimension(170, 190));

        lblNameMovie.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblNameMovie.setForeground(new java.awt.Color(255, 255, 255));
        lblNameMovie.setText("jLabel3");

        lblDescription.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription)
                    .addComponent(lblNameMovie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblNameMovie)
                .addGap(18, 18, 18)
                .addComponent(lblDescription)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblNameMovie;
    // End of variables declaration//GEN-END:variables
}
